### ISSUE TITLE
cucumber-json-formatter doesn't work in github actions

### ISSUE THREAD

**Issue by vojtech-cerveny** [a8trejo/cypress-cucumber-framework#3]
Hey, I was trying your script from  and it seems that it doesn't work properly. I tried to debug and check this - https://github.com/vojtech-cerveny/cypress-cucumber-framework/actions/runs/3548944356/jobs/5960727834

I only added `cucumber-json-formatter --help` to verify, that it works properly and it fails.
https://github.com/vojtech-cerveny/cypress-cucumber-framework/blob/master/.github/workflows/automation.yml#L40

it seems, that `cucumber-json-formatter` is not on PATH and it doesn't work. It works locally, but not on Github Actions.
Also it means, that it doesn't generate json file from `ndjson` from `cypress-preprocessor` - it is pitty that it doesn't return any error, but it is what it is :)

**Comment by vojtech-cerveny** [comment]
Ok, update: if you split steps and create separate step for PATH, after that it doesn't throw error, but formatter doesn't show anything... 🤔

**Comment by vojtech-cerveny** [comment]
+ I added artefacts into repo 
```
      - name: Store test results into artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: cypress/results/
```

and this is result: 
![Screenshot 2022-11-25 at 5 31 30 PM](https://user-images.githubusercontent.com/12935892/204025969-5213263e-e87f-4b51-85a0-53a3c92b193f.png)
